FROM node:alpine
WORKDIR /backend
COPY auth-server/package.json package.json
RUN npm i
COPY auth-server/src .
COPY auth-server/tsconfig.json .
EXPOSE 3000
RUN npm run build
CMD ["node", "build/index.js"]