FROM node:alpine
WORKDIR /backend
COPY express-todo-notes/package.json package.json
RUN npm i
COPY express-todo-notes/src .
COPY express-todo-notes/tsconfig.json .
EXPOSE 3000
RUN npm run build
CMD ["node", "build/index.js"]